### ISSUE TITLE
Add WatchOS Support

### ISSUE THREAD

**Issue by mortdiggiddy** [a2/MessagePack.swift#19]
Hello,

I really like what you have done here and I think that MessagePack.swift can be used with WatchOS 2.0 projects for communication using the WatchConnectivity Framework. Can you please introduce the watch OS target into the pod spec?
- s.watchos.deployment_target = '2.0'

Example:
https://github.com/AliSoftware/OHHTTPStubs/commit/9fb400fd90d139ec1762fcbdf15b8693d7794381

Thank you!

**Comment by a2** [comment]
Done!
