### ISSUE TITLE
Pack Dictionary

### ISSUE THREAD

**Issue by sschizas** [a2/MessagePack.swift#31]
Can you please provide me with an example how to pack a Dictionary<String, AnyObject> to msg-pack?

**Comment by prcela** [comment]
```
        let dic:[String:String] = [
            "phone": "123",
            "code": "090"
        ]

        var mpDic = [MessagePackValue:MessagePackValue]()

        for (key,value) in dic
        {
            mpDic[MessagePackValue(key)] = MessagePackValue(value)
        }

        let packed = MessagePackValue(mpDic)

        print(packed)
```

**Comment by sschizas** [comment]
Thank you very much for your reply. What if the dictionary is [String: AnyObject] ?

**Comment by a2** [comment]
@n3trino In that case, you need to figure out what time of object each value is so you can convert it to the correct `MessagePackValue` case.

**Comment by a2** [comment]
Although question was vague, it was answered. Closing until further discussion is needed.
