### ISSUE TITLE
minimum deployment target is iOS 10.3

### ISSUE THREAD

**Issue by iDevHank** [a2/MessagePack.swift#46]
Is there any issue with iOS8 or 9?
Why not change it to iOS8?

**Comment by a2** [comment]
Where are you seeing that the minimum deployment target is iOS 10.3?

**Comment by a2** [comment]
This is a problem with using the SPM-generated Xcode project. I will create a pull request that fixes this issue.

**Comment by davidlawson** [comment]
This is still seen when using Carthage on an iOS project.

**Comment by a2** [comment]
@davidlawson That's correct. I didn't tag a new release. I will do so now.

**Comment by a2** [comment]
Just tagged version [2.1.0](https://github.com/a2/MessagePack.swift/releases/tag/2.1.0) and am updating the CocoaPods spec now.
