### ISSUE TITLE
Integer overflow build Errors in XCode 9 Beta 5

### ISSUE THREAD

**Issue by litso** [a2/MessagePack.swift#52]
In `Pack.swift: packPositiveInteger` and `Pack.swift: pack`we get the following errors when comparing either `UInt64` or `UInt32` values to `0xffff_ffff`

```
Integer literal '4294967295' overflows when stored into 'Int'
```
and

```
Integer literal '4294967295' overflows when stored into signed 'Builtin.Int32'
```

**Comment by litso** [comment]
This appears to be related to 32-bit/64-bit support.
https://stackoverflow.com/questions/35329459/integer-literal-overflows-when-stored-into-int

Do we plan on supporting 32-bit platforms going forward?

**Comment by a2** [comment]
@litso, great catch on the Xcode 9 support bug, and thanks for your contributions 😄
