### ISSUE TITLE
Update for Swift 4

### ISSUE THREAD

**Issue by Narsail** [a2/MessagePack.swift#55]
Do you have a timeline when you will release a version for Swift 4?

**Comment by a2** [comment]
As far as I am aware, Swift 3.2 and 4.0 binaries can coexist in a project. That being said, the current version builds with Swift 3.2 (in Xcode 9). Are there specific Swift 4 features you would like to see though?

**Comment by Narsail** [comment]
It is more about convenience because I have a rather complex structure of modules/frameworks for our App. And I'm actually avoiding to find the best way (I'm sure there is one) how cocoa pods (especially when checking a pod spec file) can include a Swift 3.2 framework within a Swift 4 project. This problem occurs mainly when uploading a new version for my internal pod repo.

**Comment by a2** [comment]
Something [like this](https://gist.github.com/JohnSundell/519cb322978ac59f5ac161ff67e4413b) might be useful in the meantime?

**Comment by Narsail** [comment]
The Problem isn't the Podfile. For that I use a slightly modified version of your library with the link to my repo and the specific command. But I can't use that in a .podspec. That's the problem :) 

Edit: I just started a Pull Request. It might fast forward the process a bit :) #56 The only thing I'm not sure about if some of my changes add problems the test might not cover.
