### ISSUE TITLE
Compilation fails on 32bit devices

### ISSUE THREAD

**Issue by ogres** [a2/MessagePack.swift#57]
When trying to compile MessagePack for 32 bit ( iOS ) devices, following lines fail on Integer overflow 

https://github.com/a2/MessagePack.swift/blob/master/Sources/MessagePack/Pack.swift#L29
https://github.com/a2/MessagePack.swift/blob/master/Sources/MessagePack/Pack.swift#L123
https://github.com/a2/MessagePack.swift/blob/master/Sources/MessagePack/Pack.swift#L153
https://github.com/a2/MessagePack.swift/blob/master/Sources/MessagePack/Pack.swift#L91
https://github.com/a2/MessagePack.swift/blob/master/Sources/MessagePack/Pack.swift#L108

Tested on Xcode 9, Swift 3.2

**Comment by a2** [comment]
@ogres @n3trino I'm trying to reproduce the issue with Xcode 9 but I don't have a 32-bit iOS device. Is it possible to reproduce with the simulator at all?

**Comment by ogres** [comment]
Try making an archive with armv7 architecture enabled

**Comment by a2** [comment]
Hmm, I'm able to build an `armv7` framework on my machine.

<img width="427" src="https://user-images.githubusercontent.com/241156/30818048-c875ff76-a21a-11e7-974d-72b31a424cf2.png">

<img width="578" src="https://user-images.githubusercontent.com/241156/30818027-bc325066-a21a-11e7-805d-bdec925867cd.png">

**Comment by ogres** [comment]
I am able to reproduce this on an empty project.

1. Create new iOS project
2. Set min iOS version to 9
3. Install MessagePack via CocoaPods
4. Set Swift lang to 3.2 for MessagePack.swift target ( and 4.0 for the project itself )
5. Select 'Generic iOS Device' in devices list
6. Project -> Archive

**Comment by sschizas** [comment]
Hello @a2 ,

Have you tried to archive? The issue appears when you archive a project and not when you build and run either on simulator or on device.

**Comment by a2** [comment]
Ah I see the problem. This was fixed with PR #53 but I hadn't tagged a new release. Will do so later today.

**Comment by a2** [comment]
I just pushed version [2.1.1](https://github.com/a2/MessagePack.swift/releases/tag/2.1.1) to CocoaPods. Let me know if this is still an issue. 😄

**Comment by ogres** [comment]
Works fine on 32 bit device, Thanks @a2
