### ISSUE TITLE
Xcode9  carthage MessagePack

### ISSUE THREAD

**Issue by FreddyZeng** [a2/MessagePack.swift#58]
*** Building scheme "MessagePack iOS" in MessagePack.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/fanrong/ios_DeviceManager/DeviceManager/Class/Anima/Carthage/Carthage/Checkouts/MessagePack.swift/MessagePack.xcodeproj -scheme MessagePack\ iOS -configuration Release -derivedDataPath /Users/fanrong/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/MessagePack.swift/2.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/fanrong/ios_DeviceManager/DeviceManager/Class/Anima/Carthage/Carthage/Checkouts/MessagePack.swift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/qp/vvlmg9ps3zn45sx_hlvbb1_c0000gn/T/carthage-xcodebuild.IYnGn8.log

**Comment by a2** [comment]
Could you provide the additional details from the `/var/folders/qp/vvlmg9ps3zn45sx_hlvbb1_c0000gn/T/carthage-xcodebuild.IYnGn8.log` file mentioned?

**Comment by a2** [comment]
Seems like you were trying to build MessagePacks.swift version 2.1.0 with Xcode 9.0 (9A235). Issues with this combination of versions should be fixed. Feel free to reopen this issue otherwise.
