### ISSUE TITLE
Spec version?

### ISSUE THREAD

**Issue by iwasrobbed-ks** [a2/MessagePack.swift#68]
Hi there 👋 Does this follow a specific version of the spec? e.g. https://github.com/msgpack/msgpack/blob/master/spec.md

Just wondering so we make sure our backend<>client teams use the same spec.

**Comment by a2** [comment]
This is a good question! The spec does not really have version numbers, which is a problem. This repo doesn't support the timestamp extension, for example, which did not exist the last time I visited the spec. Do you have any ideas for best practices? Ideally we would be able to make sure your backend and client use the same spec.

**Comment by iwasrobbed-ks** [comment]
It looks like they are just using `v2.0` for now: https://github.com/msgpack/msgpack/pull/165

Might be worth filing an issue with them to standardize around [semantic versioning](https://semver.org/) for all the incremental changes that have occurred after 2.0 was released

**Comment by iwasrobbed-ks** [comment]
Actually, looks like there's up to a v5 at this point: https://github.com/msgpack/msgpack/issues/195

It looks like all changes have been additive up until this point (but does that include bug fixes?) https://github.com/msgpack/msgpack/issues/195#issuecomment-91518024

**Comment by iwasrobbed-ks** [comment]
Going to close this out. Just wanted to say thanks for your great work on this. It's a very clean API and well tested which makes our lives easy 💯
