### ISSUE TITLE
How do I do if I want to pack small uint32 values?

### ISSUE THREAD

**Issue by dictav** [a2/MessagePack.swift#9]
Hi,

I'm trying implement MessagePack-RPC using this library. And I need to pack a value of uint32.

I have tryed,

```
let value = MessagePackValue(1 as UInt32)
let data = MessagePack.pack(value) //=> 0x01
```

But I got a fixnum instead of uint32.

How do I do if I want to pack small uint32 values?

**Comment by a2** [comment]
Currently MessagePack.swift packs integers into as few bytes as possible. I would resist changing this because, instead of `.Int` and `.UInt` cases, there would need to be separate cases for each integral width (8, 16, 32, 64).

**Comment by shabbyrobe** [comment]
When using MessagePack as an interchange format, whether using files or sockets, there's no guarantee that a server or client on the other end of the serialisation has the same view of integers as Swift. MessagePack provides fixed integral width types for a very good reason - to facilitate this interoperation. Excluding the ability to be explicit about integer widths from the Swift implementation means that this library can't actually speak MessagePack; only some narrow idea of MessagePack as it relates to Swift.
